# Generated by Django 6.0.4 on 2026-04-17 04:25

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0002_articleimportrun"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
