# Generated by Codex on 2026-04-18

from django.db import migrations, models


def backfill_article_counts(apps, schema_editor):
    Article = apps.get_model("articles", "Article")
    for article in Article.objects.all().only("id", "content", "word_count", "char_count"):
        content = article.content or ""
        article.word_count = len(content.split())
        article.char_count = len(content)
        article.save(update_fields=["word_count", "char_count"])


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_article_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="author",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="char_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="article",
            name="word_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(backfill_article_counts, migrations.RunPython.noop),
    ]
